version: "3.9"

networks:
  database-access-frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  postgresql_db_data:
    driver: local

services:
  pgsqldb:
    build:
      context: ./Assets
      dockerfile: BuildDatabase.Dockerfile
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - database-access-frontend
      - backend

  app:
    build:
      context: .
      dockerfile: ./Assets/BuildApp.Dockerfile
    environment:
      DATABASE_CONNECTION_STRING: "Server=pgsqldb;Port=5432;Database=postgres;User Id=postgres;Password=password;"
    ports:
      - "7257:80"
    depends_on:
      pgsqldb:
        condition: service_healthy
    networks:
      - backend

  pgadmin:
   image: dpage/pgadmin4
   environment:
     PGADMIN_DEFAULT_EMAIL: "user@email.com"
     PGADMIN_DEFAULT_PASSWORD: password
     PGADMIN_LISTEN_PORT: 8080
   ports:
     - "8080:8080"
   depends_on:
     pgsqldb:
       condition: service_healthy
   restart: unless-stopped
   networks:
     - database-access-frontend
